name: map-services

networks:
  default:
  homelab-net:
    external: true

volumes:
  config_volume:

services:
  cron:
    image: docker:28-cli
    container_name: cron_scheduler
    command: sh -c "crond -f -l 2"
    working_dir: /workspace
    volumes:
      - ./crontab:/etc/crontabs/root
      - ./docker-compose.yml:/workspace/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - homelab-net

  mapproxy-config-generator:
    image: alpine
    container_name: mapproxy_config_generator
    env_file:
      - .env
    volumes:
      - ./mapproxy.template.yaml:/tmp/mapproxy.template.yaml
      - config_volume:/output
    command: >
      sh -c "
        apk add --no-cache gettext &&
        envsubst < /tmp/mapproxy.template.yaml > /output/mapproxy.yaml
      "

  mapproxy:
    container_name: mapproxy
    restart: unless-stopped
    image: ghcr.io/mapproxy/mapproxy/mapproxy:5.0.0-alpine-nginx
    depends_on:
      mapproxy-config-generator:
        condition: service_completed_successfully
    volumes:
      - config_volume:/mapproxy/config
      - ./data/mapproxy/cache_data:/mapproxy/cache_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mapproxy.entrypoints=websecure"
      - "traefik.http.routers.mapproxy.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/mapproxy/wmts/wmts`)"
      - "traefik.http.services.mapproxy.loadbalancer.server.port=80"
      - "dockflare.enable=true"
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=api.destructuring-bind.org"
      - "cloudflare.tunnel.path=/mapproxy/wmts/wmts"
      - "cloudflare.tunnel.service=http://mapproxy:80"
    networks:
      - default
      - homelab-net

  uk-weather-overlays:
    container_name: uk_weather_overlays
    image: ghcr.io/rm-hull/metoffice-uk-weather-overlays:latest
    command:
      - api-server
      - "--root=/data/metoffice-datahub"
      - "--port=8080"
    volumes:
      - ./data/metoffice-datahub:/data/metoffice-datahub
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uk-weather-overlays.entrypoints=websecure"
      - "traefik.http.routers.uk-weather-overlays.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/metoffice/datahub`)"
      - "traefik.http.services.uk-weather-overlays.loadbalancer.server.port=80"
      - "dockflare.enable=true"
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=api.destructuring-bind.org"
      - "cloudflare.tunnel.path=/v1/metoffice/datahub"
      - "cloudflare.tunnel.service=http://uk-weather-overlays:8080"
    networks:
      - default
      - homelab-net

  company-data:
    container_name: company_data
    image: ghcr.io/rm-hull/company-data-api:latest
    command:
      - api-server
      - "--db=/data/companies_data.db"
      - "--port=8080"
    volumes:
      - ./data/company-data:/data/
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.company-data.entrypoints=websecure"
      - "traefik.http.routers.company-data.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/company-data/`)"
      - "traefik.http.services.company-data.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/company-data"
      - "dockflare.service=http://company-data:8080"
    networks:
      - default
      - homelab-net

  poi-server:
    container_name: poi_server
    image: ghcr.io/rm-hull/geods-poi-api:latest
    command:
      - "poi"
      - "http-server"
      - "--db=/data/poi_uk.gpkg"
      - "--port=8080"
    volumes:
      - ./data/geods-poi/poi_uk.gpkg:/data/poi_uk.gpkg:ro
    environment:
      - UNSPLASH_ACCESS_KEY
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poi-server.entrypoints=websecure"
      - "traefik.http.routers.poi-server.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/geods-poi/`)"
      - "traefik.http.services.poi-server.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/geods-poi"
      - "dockflare.service=http://poi-server:8080"
    networks:
      - default
      - homelab-net

  postcode-polygons:
    container_name: postcode_polygons
    image: ghcr.io/rm-hull/postcode-polygons:latest
    command:
      - api-server
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postcode-polygons.entrypoints=websecure"
      - "traefik.http.routers.postcode-polygons.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/postcode/`)"
      - "traefik.http.services.postcode-polygons.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/postcode"
      - "dockflare.service=http://postcode-polygons:8080"
    networks:
      - default
      - homelab-net

  street-manager-relay:
    container_name: street_manager_relay
    image: ghcr.io/rm-hull/street-manager-relay:latest
    command:
      - api-server
      - "--db=/data/street-manager.db"
      - "--port=8080"
    volumes:
      - ./data/street-manager-relay:/data
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.street-manager-relay.entrypoints=websecure"
      - "traefik.http.routers.street-manager-relay.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/street-manager-relay/`)"
      - "traefik.http.services.street-manager-relay.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/treet-manager-relay"
      - "dockflare.service=http://street-manager-relay:8080"
    networks:
      - default
      - homelab-net
