name: map-services

networks:
  default:
  homelab-net:
    external: true

volumes:
  config_volume:

services:
  cron:
    image: docker:28-cli
    container_name: cron_scheduler
    command: >
      sh -c "
        cp /workspace/crontab /var/spool/cron/crontabs/root &&
        chown root /var/spool/cron/crontabs/root &&
        chmod 600 /var/spool/cron/crontabs/root &&
        crontab -l &&
        crond -f -l 2
      "
    working_dir: /workspace
    volumes:
      - ./.env:/workspace/.env:ro
      - ./crontab:/workspace/crontab:ro
      - ./docker-compose.yml:/workspace/docker-compose.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - homelab-net

  du-exporter:
    container_name: du_exporter
    image: ghcr.io/rm-hull/du-exporter:latest
    command:
      - "--root=/data"
      - "--port=8080"
    volumes:
      - ./data:/data:ro
    restart: always
    healthcheck:
      disable: false
    networks:
      - default
      - homelab-net

  mapproxy-config-generator:
    image: alpine
    container_name: mapproxy_config_generator
    environment:
      - OS_DATAHUB_API_KEY=${OS_DATAHUB_API_KEY}
    volumes:
      - ./mapproxy.template.yaml:/tmp/mapproxy.template.yaml
      - config_volume:/output
    command: >
      sh -c "
        apk add --no-cache gettext &&
        envsubst < /tmp/mapproxy.template.yaml > /output/mapproxy.yaml
      "

  mapproxy:
    container_name: mapproxy
    restart: unless-stopped
    image: ghcr.io/mapproxy/mapproxy/mapproxy:5.0.0-alpine-nginx
    depends_on:
      mapproxy-config-generator:
        condition: service_completed_successfully
    volumes:
      - config_volume:/mapproxy/config
      - ./data/mapproxy/cache_data:/mapproxy/cache_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mapproxy.entrypoints=websecure"
      - "traefik.http.routers.mapproxy.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/mapproxy/wmts/wmts`)"
      - "traefik.http.services.mapproxy.loadbalancer.server.port=80"
      - "dockflare.enable=true"
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=api.destructuring-bind.org"
      - "cloudflare.tunnel.path=/mapproxy/wmts/wmts"
      - "cloudflare.tunnel.service=http://mapproxy:80"
    networks:
      - default
      - homelab-net

  uk-weather-overlays:
    container_name: uk_weather_overlays
    image: ghcr.io/rm-hull/metoffice-uk-weather-overlays:latest
    command:
      - "api-server"
      - "--root=/data/metoffice-datahub"
      - "--port=8080"
    volumes:
      - ./data/metoffice-datahub:/data/metoffice-datahub
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uk-weather-overlays.entrypoints=websecure"
      - "traefik.http.routers.uk-weather-overlays.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/metoffice/datahub`)"
      - "traefik.http.services.uk-weather-overlays.loadbalancer.server.port=80"
      - "dockflare.enable=true"
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=api.destructuring-bind.org"
      - "cloudflare.tunnel.path=/v1/metoffice/datahub"
      - "cloudflare.tunnel.service=http://uk-weather-overlays:8080"
    networks:
      - default
      - homelab-net

  uk-weather-download:
    container_name: uk_weather_download
    image: ghcr.io/rm-hull/metoffice-uk-weather-overlays:latest
    command:
      - "download"
      - "--root=/data/metoffice-datahub"
    volumes:
      - ./data/metoffice-datahub:/data/metoffice-datahub
    environment:
      - METOFFICE_DATAHUB_API_KEY=${METOFFICE_DATAHUB_API_KEY}
      - METOFFICE_ORDER_ID=${METOFFICE_ORDER_ID}
    restart: no
    healthcheck:
      disable: true

  company-data:
    container_name: company_data
    image: ghcr.io/rm-hull/company-data-api:latest
    command:
      - "api-server"
      - "--db=/data/companies_data.db"
      - "--port=8080"
    volumes:
      - ./data/company-data:/data/
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.company-data.entrypoints=websecure"
      - "traefik.http.routers.company-data.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/company-data/`)"
      - "traefik.http.services.company-data.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/company-data"
      - "dockflare.service=http://company-data:8080"
    networks:
      - default
      - homelab-net

  company-data-import:
    container_name: company_data_import
    image: ghcr.io/rm-hull/company-data-api:latest
    command:
      - "import-companies-house"
      - "--db=/data/companies_data.db"
      - "--zip-file=https://download.companieshouse.gov.uk/BasicCompanyDataAsOneFile-{{yyyy}}-{{mm}}-01.zip"
      # See: https://download.companieshouse.gov.uk/en_output.html
    volumes:
      - ./data/company-data:/data/
    restart: no
    healthcheck:
      disable: true

  code-point-import:
    container_name: code_point_import
    image: ghcr.io/rm-hull/company-data-api:latest
    command:
      - "import-code-point"
      - "--db=/data/companies_data.db"
      - "--zip-file=https://api.os.uk/downloads/v1/products/CodePointOpen/downloads?area=GB&format=CSV&redirect"
      # See: https://osdatahub.os.uk/downloads/open/CodePointOpen
    volumes:
      - ./data/company-data:/data/
    restart: no
    healthcheck:
      disable: true

  poi-server:
    container_name: poi_server
    image: ghcr.io/rm-hull/geods-poi-api:latest
    command:
      - "poi"
      - "http-server"
      - "--db=/data/poi_uk.gpkg"
      - "--port=8080"
    volumes:
      - ./data/geods-poi/poi_uk.gpkg:/data/poi_uk.gpkg:ro
    environment:
      - UNSPLASH_ACCESS_KEY=${UNSPLASH_ACCESS_KEY}
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poi-server.entrypoints=websecure"
      - "traefik.http.routers.poi-server.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/geods-poi/`)"
      - "traefik.http.services.poi-server.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/geods-poi"
      - "dockflare.service=http://poi-server:8080"
    networks:
      - default
      - homelab-net

  postcode-polygons:
    container_name: postcode_polygons
    image: ghcr.io/rm-hull/postcode-polygons:latest
    command:
      - api-server
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postcode-polygons.entrypoints=websecure"
      - "traefik.http.routers.postcode-polygons.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/postcode/`)"
      - "traefik.http.services.postcode-polygons.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/postcode"
      - "dockflare.service=http://postcode-polygons:8080"
    networks:
      - default
      - homelab-net

  street-manager-relay:
    container_name: street_manager_relay
    image: ghcr.io/rm-hull/street-manager-relay:latest
    command:
      - api-server
      - "--db=/data/street-manager.db"
      - "--port=8080"
    volumes:
      - ./data/street-manager-relay:/data
    restart: always
    healthcheck:
      disable: false
    environment:
      - SENTRY_DSN=${STREET_MANAGER_RELAY_SENTRY_DSN}
      - MODE=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.street-manager-relay.entrypoints=websecure"
      - "traefik.http.routers.street-manager-relay.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/street-manager-relay/`)"
      - "traefik.http.services.street-manager-relay.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/street-manager-relay"
      - "dockflare.service=http://street-manager-relay:8080"
    networks:
      - default
      - homelab-net

  place-names:
    container_name: place_names
    image: ghcr.io/rm-hull/placenames-api:latest
    command:
      - api-server
      - "--file=/data/placenames_with_relevancy.csv.gz"
      - "--port=8080"
      - "--top-k=10"
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.place-names.entrypoints=websecure"
      - "traefik.http.routers.place-names.rule=Host(`api.homelab.destructuring-bind.org`) && PathPrefix(`/v1/place-names/`)"
      - "traefik.http.services.place-names.loadbalancer.server.port=8080"
      - "dockflare.enable=true"
      - "dockflare.hostname=api.destructuring-bind.org"
      - "dockflare.path=/v1/place-names"
      - "dockflare.service=http://place-names:8080"
    networks:
      - default
      - homelab-net
